### PR TITLE
Add sell popup exception handling

### PR DESCRIPTION
**Pull request by hskim881028**
### Description
If there is a decimal point in the total amount, the notification popup is displayed and then returned.

### How to test
Set the price to the decimal point and then press the Enter. 

### Related Links
#468 

### Required Reviewers
@planetarium/9c-dev , @Namyujeong 

### Screenshot

image

### CODE REVIEW

**Comment by Namyujeong** [comment]
@hskim881028 I think a one-line popup would be better than a one-button popup. Is that possible?

**Comment by hskim881028** [comment]
> popup.

I agree. I will change the popup type.

**Comment by hskim881028** [comment]
> @hskim881028 I think a one-line popup would be better than a one-button popup. Is that possible?

I agree. I will change the popup type.

**Review by Namyujeong — APPROVED** [review]
It has been fixed so that when entering the total price so that it is 2 decimal places and then pressing enter, it does not move to the next.

**Pull request closed without merging**
