### PR TITLE
Bump lib9c

### PR DESCRIPTION
**Pull request by tkiapril**
[Recently, maximum supply cap and total supply tracking was introduced in `Currency` in Libplanet.](https://github.com/planetarium/libplanet/pull/2200) This introduced changes in `IAccountStateDelta` interface and how `Currency` is defined. [lib9c#1308](https://github.com/planetarium/lib9c/pull/1308) incorporates the API changes to lib9c, and this PR applies the changes to NineChronicles.

~~Resolution order: planetarium/libplanet#2225 -> planetarium/lib9c#1308 -> planetarium/NineChronicles.Headless#1497 & https://github.com/planetarium/NineChronicles/pull/1838~~

Related: planetarium/lib9c#1331, planetarium/NineChronicles.Headless#1518

### CODE REVIEW

**Review by dahlia — COMMENTED** [review]
[One of checks seems failing][1] due to version mismatch between submodule's Liblanet and bundled Libplanet assemblies… 🤔 

- Libplanet submdoule: 0.40.0
- *Libplanet.Net.dll*: 0.41.0-dev.20220825055043+494a9ed
- *Libplanet.RocksDBStore.dll*: 0.41.0-dev.20220825055043+494a9ed
- *Libplanet.Stun.dll*: 0.41.0-dev.20220825055043+494a9ed
- *Libplanet.dll*: 0.41.0-dev.20220825055043+494a9ed

[1]: https://github.com/planetarium/NineChronicles/runs/8011137177?check_suite_focus=true#step:8:18

**Comment by tkiapril** [comment]
> One of checks seems failing due to version mismatch between submodule's Liblanet and bundled Libplanet assemblies… 🤔
> 
>     * Libplanet submdoule: 0.40.0
> 
>     * _Libplanet.Net.dll_: 0.41.0-dev.20220825055043+494a9ed
> 
>     * _Libplanet.RocksDBStore.dll_: 0.41.0-dev.20220825055043+494a9ed
> 
>     * _Libplanet.Stun.dll_: 0.41.0-dev.20220825055043+494a9ed
> 
>     * _Libplanet.dll_: 0.41.0-dev.20220825055043+494a9ed

Yes, I bundled the binaries in the Github Actions artifact, but the CI script for `NineChronicles` seems to require released builds. I'll try again after releasing libplanet 0.41.0.

**Review by boscohyun — APPROVED** [review]

**Review by dahlia — APPROVED** [review]

**Review by boscohyun — APPROVED** [review]

**Review by sonohoshi — APPROVED** [review]

**Pull request merged**
