### PR TITLE
Broken Unity Hub link on README Updated.

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #6056

### CODE REVIEW

**Comment by Brijeshthummar02** [comment]
Share feedback for current pull request, and if it's fine than please do me a favor merge it in oct 1-2 when hacktoberfest starts so that i can claim merge request.

**Review by eugene-doobu — APPROVED** [review]

**Comment by Brijeshthummar02** [comment]
@moreal , @boscohyun , @Atralupus need update on this pr.

**Comment by moreal** [comment]
@Brijeshthummar02 Could you rebase this branch on the latest HEAD of the base branch?

**Review by jonny-jeahyunchoi — APPROVED** [review]

**Review by boscohyun — APPROVED** [review]

**Comment by boscohyun** [comment]
Thanks for your contribution! We're now operating `Modathon 2024` (Nine Chronicles Hackathon) with a prize pool about **$10,000**. If you're interested, please take a look at the following items 🙏🏻:

https://dorahacks.io/hackathon/planetarium-2024modathon/detail
https://planetarium.dev/discord

**Comment by Brijeshthummar02** [comment]
@boscohyun yeah sure, it's great news i'll be looking forward to it, also i have taken part in sih'24.

**Pull request merged**
