### PR TITLE
Update to English language text

### PR DESCRIPTION
**Pull request by EdwardAThomson**
### Description
1. Fixed some typos and grammar issues with the main English text of the game. A few name's were updated too.
  1.  Some item names were missing their elemental names, so I added that.
  1. Renamed a few things, e.g. Astute became Strong. This is due to the word 'Astute' feeling misplaced from an English language perspective.
  1. A couple enemy names were mistyped (e.g. Saehrimnir, but I see this was also recently updated in the main dev repo, so check for conflicts).
1. No new features added.

This is work done by CleanNeedles and I, with some checking by Naomi already in Google Doc.

Let me know if there are major conflicts with this PR and I can figure out a way to make a clean repo and then create a new PR.

### How to test
N/A

### Related Links
* [Google Doc (access request required)](https://docs.google.com/document/d/1cTT8MWwxseeA3FBqondE0LWmjEpA6vzyApa9BOyLoGA/edit)

### Required Reviewers
* Namyujeong 
* @planetarium/nine-chronicles-engineers

### Screenshot
N/A?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200562163673460) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by boscohyun** [comment]
Thanks for your first contributes! 🥳
And there are some conflicts! 😅

**Comment by Namyujeong** [comment]
I'll try to remove the conflicts in this week

**Comment by EdwardAThomson** [comment]
> I'll try to remove the conflicts in this week

Great! We can go with your spelling of Saehrimnir! I made my changes a couple months ago when we were still talking about it (and the old name was still in use back then).

**Review by Namyujeong — APPROVED** [review]
Huge conflict. I've cleared all conflicts just now. thx!

**Pull request merged**
