### PR TITLE
Improve text size in login popup - CreateAccount

### PR DESCRIPTION
**Pull request by sonohoshi**
### Description
In the previous LoginPopup-CreateAccount UI, the size of the password text entered and the size of the reconfirmation text were different, which made it uncomfortable.

### How to test
1. Check that the password text entered in the CreateAccount UI and the reconfirm text are the same size.

### Screenshot
__Before__
image
__After__
image

### CODE REVIEW

**Review by boscohyun — APPROVED** [review]

**Comment by Unengine** [comment]
Text material seems to be changed. Is it intended?

**Comment by sonohoshi** [comment]
> Text material seems to be changed. Is it intended?

If you mean fixedMarginOption, that is not intended.
I am checking what is that. However, it does not seem to affect the UI itself.

I erased the option and tested it again, but nothing changed.

**Comment by Unengine** [comment]
> > Text material seems to be changed. Is it intended?
> 
> If you mean fixedMarginOption, that is not intended.
> I am checking what is that. However, it does not seem to affect the UI itself.
> 
> I erased the option and tested it again, but nothing changed.

I think i misunderstood the structure of this prefab. I thought this text is `TextMeshProUGUI`, but it was `Text`.
In this case I mean, text color seems to be changed. Is it intended?

**Comment by sonohoshi** [comment]
> I think i misunderstood the structure of this prefab. I thought this text is TextMeshProUGUI, but it was Text.
> In this case I mean, text color seems to be changed. Is it intended?

In this prefab, using input field of ugui text. So you can misunderstand.
I changed just size and position of text, not color.

If I had changed the color, you could have confirmed that 'm_color' had changed in text of this prefab.

**Review by Unengine — APPROVED** [review]

**Pull request merged**
