### PR TITLE
Add speech bubble to combination main

### PR DESCRIPTION
**Pull request by sonohoshi**
### Description

SSIA

### How to test

Enter to combination main UI.

### Related Links

[[제작] 제작 메인에서 고양이 말풍선 UI 추가 필요](https://app.asana.com/0/958521740385861/1200833060744671/f)

### Screenshot

210908_msg combi

### CODE REVIEW

**Review by Unengine — APPROVED** [review]

**Review by Namyujeong — CHANGES_REQUESTED** [review]
- Plz replace common.csv line 979 (I couldn't push to your remote branch)
- If the width of the speech bubble needs to be longer than a certain width, set the maximum width of the speech bubble so that it can be added linebreak on its own.

```
SPEECH_COMBINE_EQUIPMENT_0,Are we here to make equipment? Cooking and upgrades are also very helpful in combat.,장비를 만들러 왔나? 요리 제작이나 강화도 큰 도움이 된다네.,Estamos aqui para fazer equipamento? Cozinhar e atualizações também são muito úteis em combate.,,私たちは機器を作るためにここにいますか？調理とアップグレードも戦闘で非常に役立ちます。,"Sind wir hier, um Ausrüstung zu machen? Kochen und Upgrades sind auch im Kampf sehr hilfreich.",¿Estamos aquí para hacer equipo? Cocinar y actualizaciones también son muy útiles en combate.,เราอยู่ที่นี่เพื่อสร้างอุปกรณ์หรือไม่ การทำอาหารและการอัพเกรดก็มีประโยชน์มากในการต่อสู้,"Czy jesteśmy tutaj, aby zrobić sprzęt? Gotowanie i aktualizacje są również bardzo pomocne w walce.","Ar mes esame čia, kad padarytume įrangą? Virimo ir atnaujinimai taip pat yra labai naudingi kovoje.",Zijn we hier om apparatuur te maken? Koken en upgrades zijn ook erg handig in Combat.,Apakah kita di sini untuk membuat peralatan? Memasak dan upgrade juga sangat membantu dalam pertempuran.,Sommes-nous ici pour faire du matériel? La cuisson et les mises à niveau sont également très utiles au combat.,"Мы здесь, чтобы сделать оборудование? Приготовление пищи и обновления также очень полезно в бою.",តើយើងមកទីនេះដើម្បីបង្កើតឧបករណ៍ទេ? ការចំអិនម្ហូបនិងការធ្វើឱ្យប្រសើរក៏មានប្រយោជន៍ខ្លាំងផងដែរក្នុងការប្រយុទ្ធ។,,我们在这里制作设备吗？烹饪和升级在战斗中也非常有用。,
```

**Comment by sonohoshi** [comment]
> * Plz replace common.csv line 979 (I couldn't push to your remote branch)
> * If the width of the speech bubble needs to be longer than a certain width, set the maximum width of the speech bubble so that it can be added linebreak on its own.
> 
> ```
> SPEECH_COMBINE_EQUIPMENT_0,Are we here to make equipment? Cooking and upgrades are also very helpful in combat.,장비를 만들러 왔나? 요리 제작이나 강화도 큰 도움이 된다네.,Estamos aqui para fazer equipamento? Cozinhar e atualizações também são muito úteis em combate.,,私たちは機器を作るためにここにいますか？調理とアップグレードも戦闘で非常に役立ちます。,"Sind wir hier, um Ausrüstung zu machen? Kochen und Upgrades sind auch im Kampf sehr hilfreich.",¿Estamos aquí para hacer equipo? Cocinar y actualizaciones también son muy útiles en combate.,เราอยู่ที่นี่เพื่อสร้างอุปกรณ์หรือไม่ การทำอาหารและการอัพเกรดก็มีประโยชน์มากในการต่อสู้,"Czy jesteśmy tutaj, aby zrobić sprzęt? Gotowanie i aktualizacje są również bardzo pomocne w walce.","Ar mes esame čia, kad padarytume įrangą? Virimo ir atnaujinimai taip pat yra labai naudingi kovoje.",Zijn we hier om apparatuur te maken? Koken en upgrades zijn ook erg handig in Combat.,Apakah kita di sini untuk membuat peralatan? Memasak dan upgrade juga sangat membantu dalam pertempuran.,Sommes-nous ici pour faire du matériel? La cuisson et les mises à niveau sont également très utiles au combat.,"Мы здесь, чтобы сделать оборудование? Приготовление пищи и обновления также очень полезно в бою.",តើយើងមកទីនេះដើម្បីបង្កើតឧបករណ៍ទេ? ការចំអិនម្ហូបនិងការធ្វើឱ្យប្រសើរក៏មានប្រយោជន៍ខ្លាំងផងដែរក្នុងការប្រយុទ្ធ។,,我们在这里制作设备吗？烹饪和升级在战斗中也非常有用。,
> ```

OK. I checked it. I'll reflect it.

**Comment by Namyujeong** [comment]
image

The width of the speech bubble is still too long. On what basis are speech bubbles being auto-sized?

**Comment by sonohoshi** [comment]
I'll check it again.

**Comment by Namyujeong** [comment]
I was checking on the previous branch.
✅  The width of the speech bubble has been adjusted well.
⚠️ When the speech bubble disappears, a strange afterimage of the speech is visible once. (00:02)
⚠️ After moving to the main screen, an afterimage of the speech bubble is visible once too. (00:07)

https://user-images.githubusercontent.com/41294407/132664634-8e8e8de5-285f-4a19-bfeb-1b4ff8dc8f5c.mov

**Comment by sonohoshi** [comment]
> Sorry, I was checking on the previous branch.
> ✅ The width of the speech bubble has been adjusted well.
> ⚠️ When the speech bubble disappears, a strange afterimage of the speech is visible once. (00:02)
> ⚠️ After moving to the main screen, an afterimage of the speech bubble is visible once too. (00:07)

Have identified the cause of the two bugs. I'll fix it.

**Comment by sonohoshi** [comment]
> Sorry, I was checking on the previous branch.
> ✅ The width of the speech bubble has been adjusted well.
> ⚠️ When the speech bubble disappears, a strange afterimage of the speech is visible once. (00:02)
> ⚠️ After moving to the main screen, an afterimage of the speech bubble is visible once too. (00:07)

I'm sorry for my inexperienced work. Can you check it out again?

**Review by Namyujeong — APPROVED** [review]
It successfully works!

**Pull request merged**
