### PR TITLE
Update dialog.csv

### PR DESCRIPTION
**Pull request by Oremal**
Add and Fix french and english translation (mostly on the last part : fire dungeon)

### Description

1. Problems to solve.
2. Features to add.

### How to test

1. First step.

### Related Links
0xeD40527E9FB58D436Be38418cffe0000c7574ea8

### CODE REVIEW

**Comment by Namyujeong** [comment]
@Oremal Thank you for your contribution! Could you change the target branch of all the PRs you uploaded to `development` ?

**Comment by Oremal** [comment]
@Namyujeong Hi, sorry I never used git hub before! I made the change is it fine now ?

**Comment by Namyujeong** [comment]
@Oremal Thank you again! However, if this pops up, the correction is wrong. The problem is that the file version is not correct.
image

Here are the latest localization files. Could you revise it based on this and upload it again?
Perhaps you would be more comfortable closing these PRs and uploading them anew.
https://github.com/planetarium/NineChronicles/tree/development/nekoyume/Assets/StreamingAssets/Localization

**Comment by Oremal** [comment]
@Namyujeong I think i resolved the conflict (at least there is no error message anymore), could you check if it's i did it right before I change the other ? (thanks a lot, and sorry for the trouble)

**Review by Namyujeong — APPROVED** [review]

**Comment by Namyujeong** [comment]
@Oremal Good, you can do it like this! Plz fix other PR too.

**Pull request merged**
