### PR TITLE
refactor: BlockHashCache

### PR DESCRIPTION
**Pull request by boscohyun**
SSIA

image

### CODE REVIEW

**Review by jonny-jeahyunchoi — APPROVED** [review]

**Comment by riemannulus** [comment]
Since [`Libplanet 3.5`](https://github.com/planetarium/libplanet/releases/tag/3.5.0), using `StateRootHash` instead of `BlockHash` if you want to represent state's pointer.

- `BlockHash` is represent the `Block`'s pointer.
- Of course, `Block` have there own the `StateRootHash` execute after that, but it contain useless overhead. (e.g., Derive `StateRootHash` from `BlockHash` tasks.)
- And the `StateRootHash` what derived from `BlockHash` is just represent end of block. not each end of action execute.

So, I suggest caching `StateRootHash` insetead of `BlockHash`. if you needed.

Be sure, I do not say this PR is meaningless. Just notice for your next tasks. 😃

**Comment by boscohyun** [comment]
@riemannulus Thanks for your kind explanation. I'll reflect that separately.🙂

**Comment by riemannulus** [comment]
fyi: `BlockHash` coming from the `Render` event was useless. Because it is `PreviousBlockHash` not `BlockHash`.

If you retrieve the `BlockHash` from `IAgent` using the `BlockIndex` retrieved from the render event, it will be different from the `BlockHash` provided by the render event. AFAIK these `BlockHashCache` needs are from this problem.
But `StateRootHash` is not, it represents exactly what you want. So you can cache `StateRootHash` in the render event.

**Comment by boscohyun** [comment]
@riemannulus That's important.. I'll convert this to draft and work some. Thanks!

**Comment by boscohyun** [comment]
@riemannulus I changed the target branch from `development` to feature branch. And.. caching the state root hash if possible.

**Pull request merged**
