### PR TITLE
Use Address.Equals(Address) instead comparing as raw format

### PR DESCRIPTION
**Pull request by umardevX**

### CODE REVIEW

**Comment by moreal** [comment]
> @sonohoshi it breaks idk why? you can guide me if i need a new PR to create with new changes.

@umardevX It is Unity-issue. Unity requires license key and secrets cannot be shared with PRs from forked repository. So this pull request should be manually reviewed by maintainers of this repository.

**Comment by umardevX** [comment]
@moreal What next i can do to close this PR?

**Comment by sonohoshi** [comment]
> @sonohoshi it breaks idk why? you can guide me if i need a new PR to create with new changes.
@umardevX 
Sorry for the late confirmation. Thank you so much for your contribution. I'll review it ASAP!

**Review by sonohoshi — APPROVED** [review]
LGTM

**Comment by umardevX** [comment]
@sonohoshi  Thanks

**Pull request merged**
